#!/bin/bash

set -euo pipefail

die() {
  >&2 echo $1 
  exit 1
}

[[ -n "$1" ]] || die "no path to keybox provided"
[[ -f "$1" ]] || die "can't read key at $1"

[[ -n "$2" ]] || die "no uid provided"

kbx=$(mktemp --suffix '.kbx')
finish() {
  rm "$kbx"
}
trap finish EXIT

gpg2 --no-default-keyring --keyring "$kbx" --import "$1" 
gpg2 --no-default-keyring --keyring "$kbx" --edit-key "$2"

