#!/bin/bash

set -euo pipefail

die() {
  >&2 echo $1 
  exit 1
}

[[ -n "$1" ]] || die "no path to key provided"
[[ -f "$1" ]] || die "can't read key at $1"

[[ -n "$2" ]] || die "no uid provided"

kbx=$(mktemp --suffix '.kbx')
finish() {
  rm "$kbx"
}
trap finish EXIT

secret=$(mktemp)
public=$(mktemp)

gpg2 --no-default-keyring --keyring "$kbx" --import $1 
gpg2 --no-default-keyring --keyring "$kbx" --edit-key $2
gpg2 --no-default-keyring --keyring "$kbx" --armor --export-secret-keys $2 >"$secret"
gpg2 --no-default-keyring --keyring "$kbx" --armor --export $2 >"$public"

echo "$secret"
echo "$public"
